import React from 'react';
import '../styles/Termsandcondition.css';

const TermsAndConditions = () => {
  return (
    <div className="terms-container">
      <header className="terms-header">
        <div className="header-content">
          <h1>Terms and Conditions</h1>
          <button className="back-button" onClick={() => window.history.back()}>
            ← Back
          </button>
        </div>
        <div className="last-updated-header">
          Last updated on 15th November 2025
        </div>
      </header>

      <main className="terms-content">
        <div className="document-title">
          Flyhub END-USER TERMS AND CONDITIONS
        </div>

        <div className="intro-note">
          In terms of Information Technology Act 2000, this document is an electronic record. Being generated by a computer system, it does not require any physical or digital signatures.
        </div>

        <div className="section-divider"></div>

        <div className="terms-section">
          <p>
            The Flyhub internet resource marketplace, Flyhub Mobile Application services (hereinafter referred to as the "Platform") is owned by Flytutor Technologies Private Limited, having its registered office at 175 & 176, Dollors Colony, JP Nagar, Bannerghatta Main Road, Bengaluru - 560 076 (hereinafter referred to as "Company"/"Flyhub"). This document in its present form is the property of Flytutor Technologies Private Limited and shall belong to Flytutor Technologies Private Limited, its subsidiaries and assigns as may be created from time to time.
          </p>
        </div>

        <div className="section-title">GENERAL</div>
        <div className="terms-section">
          <p>
            By accepting these Terms, you are entering into a legally binding Agreement ("Agreement") with us.
          </p>
          <p>
            This Agreement consists of the following terms and conditions (hereinafter the "General Terms") and terms and conditions specific to use of individual Services (hereinafter the "Service Specific Terms"). The General Terms and Service Specific Terms are collectively referred to as the "Terms". In the event of a conflict between the General Terms and Service Specific Terms, the Service Specific Terms shall prevail.
          </p>
          <p>
            These Terms, along with the others found on our Platform, include our policy for acceptable use of the Platform, its content, the content posted on the Platform, your rights, your obligations as well as restrictions regarding your use of the Platform.
          </p>
          <p>
            When you access, browse or use the Platform, you accept, without limitation or qualification, the terms and conditions set forth herein. When you access or use any of the Services, you will be subject to the rules, regulations, policies and all applicable terms and conditions which shall be deemed to be incorporated into and be a part and parcel of these Terms. When you access any subsite or any other mobile application (whether belonging to an associate of the company or otherwise) through this Platform, such subsite or mobile application may have its own terms and conditions which are specific to thereto.
          </p>
          <p>
            We may modify these Terms from time to time and such modification will be effective upon posting on the Platform. You agree to be bound to any changes to these Terms when you use the Platform after any such modification is posted. It is important that you review these Terms regularly to ensure you are updated as to any changes made.
          </p>
          <p>
            So long as you comply with these Terms and the Service specific Terms, the Company grants you a non-exclusive, non-transferable, limited right to enter, view and use this Platform and/or avail Services.
          </p>
        </div>

        <div className="section-title">DEFINITIONS</div>
        <div className="terms-section">
          <ul className="definition-list">
            <li><strong>"Account"</strong> shall mean the account created by the Customer on the Platform for availing the Services provided by Flyhub.</li>
            <li><strong>"Applicable Laws"</strong> shall mean any statute, law, regulation, ordinance, rule, judgment, notification, rule of common law, order, decree, bylaw, government approval, directive, guideline or any interpretation, policy or administration having the force of law in India by any authority having jurisdiction over the matter in question, whether in effect as of the date of this Agreement or thereafter and the word "Laws" shall be construed accordingly.</li>
            <li><strong>"Application"</strong> shall mean the mobile application "Flyhub" as updated by Flytutor Technologies from time to time.</li>
            <li><strong>"Content"</strong> refers to any text, image, graphic, video, audio or all forms of data which are made available on the Platform.</li>
            <li><strong>"Customer", "You", "User"</strong> shall mean the natural person who has gained access to the Platform by providing Registration Data while registering for Services.</li>
            <li><strong>"Intellectual Property Rights"</strong> refers to all intellectual property rights and all analogous rights subsisting under the laws of each and every jurisdiction throughout the world and intellectual property for the full term of the rights concerned and including all extensions and renewals of such rights, whether or not such rights are registered or capable of registration, including without limitation copyrights, trademarks, trade names, service marks, service names, patents, designs, and all other proprietary rights of whatsoever description whether or not protected and whether or not capable of protection.</li>
            <li><strong>"Platform"</strong> shall mean the online marketplace accessible at www.flyhub.in/marketplace.html, the Flyhub mobile application, as well as the services made available by Flyhub.</li>
            <li><strong>"Registration Data"</strong> shall mean the mandatory and optional data that is submitted by Users to browse the Platform and/or avail the Services, which includes data related to your drones.</li>
            <li><strong>"Services"</strong> shall mean the provision of an online marketplace for drone-related sales, parts, accessories, hiring of pilots, UAV jobs, drone rentals, drone service, drone training and drone-related news by Flyhub through the Platform.</li>
            <li><strong>"Terms", "Terms and conditions", "Policy" etc.</strong> shall mean the entire Terms of Use and all parallel policies that apply for the use of our Platform or availing our Services.</li>
            <li><strong>"Your Content"</strong> refers to any content submitted by way of registration or in connection with use of the Platform or for availing Services.</li>
            <li><strong>"Flyhub" or "us" or "we" or "our"</strong> shall mean Flytutor Technologies Private Limited.</li>
          </ul>
        </div>

        <div className="section-title">PRIVACY POLICY</div>
        <div className="terms-section">
          <p>
            Our General Privacy Policy is separately available on the Platform and can be perused by you at your convenience here: www.flyhub.in/privacypolicy.html
          </p>
        </div>

        <div className="section-title">ELIGIBILITY</div>
        <div className="terms-section">
          <p>
            You must be of legal age to enter into a binding agreement in order to accept the Terms.
          </p>
          <p>
            Without limitation to the foregoing, in the event you are barred from undertaking legally binding obligations under the Indian Contract Act, 1872, or are for any reason, unable to provide Consent as per the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011, you are not eligible to register for use or avail the services available on the Platform.
          </p>
          <p>
            Notwithstanding the aforementioned, the minimum age of Users must be 18 years.
          </p>
        </div>

        <div className="section-title">REGISTRATION AS A USER</div>
        <div className="terms-section">
          <p>
            The browsing of the Platform, including the Services offered therein is available to registered Users.
          </p>
          <p>
            To become a registered User, you must be eligible and will be required to provide Registration Data. You represent and warrant that all information you supply to us about yourself and others (including Registration Data) is true and accurate.
          </p>
          <p>
            If you provide any information that is untrue, inaccurate, out of date or incomplete, or becomes untrue, inaccurate, out of date or incomplete, or we have reasonable grounds to suspect that the information provided by you is untrue, inaccurate, out of date or incomplete, we may in our sole discretion discontinue the provision of the Services to you or discontinue your access to the Platform by suspending or terminating your Account.
          </p>
          <p>
            By providing Registration Data, you agree to undergo a Registration Data verification process which may include you providing One Time Password (OTP) to verify your mobile number and verifying your email id using the verification link sent to the email address you provide as part of Registration Data.
          </p>
          <p>
            It is hereby reiterated that all data you provided including without limitation Registration Data shall be subject to the terms set forth in our Privacy Policy and you represent and warrant that you have the absolute right and authority to provide such data.
          </p>
          <p>
            In the event you find any content on the website which you deem is unlawful, libellous, defamatory, obscene, pornographic, indecent, lewd, suggestive, harassing, threatening, invasive of privacy or publicity rights, abusive, inflammatory, fraudulent or otherwise objectionable against any religious beliefs, spam, potentially infringing or is not authorized by the intellectual property rights owner, or is violative of any applicable law, you are requested to report such content to sales@flyhub.in. On receiving such report, the company reserves the right to investigate and/or take such action as the company may deem appropriate.
          </p>
        </div>

        <div className="section-title">USER ACCOUNT</div>
        <div className="terms-section">
          <p>
            You are allowed to create and operate only one Account using the Registration Data. In case You are unable to access Your Account or suspect any unauthorized use of Your Account, please inform us at sales@flyhub.in and make a written request for blocking Your Account. We will not be liable for any unauthorized transactions made through Your Account prior to the resolution of your request.
          </p>
          <p>
            You are solely responsible for maintaining the confidentiality of your Registration Data and will be liable for all activities and transactions that occur through Your Account, whether initiated by You or any third party. Your Account cannot be transferred, assigned or sold to a third party. We shall not be liable for any loss that You may incur as a result of someone else using Your password or Account, either with or without Your knowledge.
          </p>
          <p>
            If your Account has been compromised or we have reasonable grounds to suspect that your Account has been compromised, we may in our sole discretion discontinue the provision of the Services to you or discontinue your access to the Platform by suspending or terminating your Account.
          </p>
        </div>

        <div className="section-title">SERVICES</div>
        <div className="terms-section">
          <p>
            The Platform provides inter alia users with access to an online marketplace for drone-related products and services. This includes but is not limited to the sale of drones, parts and accessories, a platform to hire pilots and find UAV jobs, drone rentals and drone services, drone training programs and access to drone-related news.
          </p>
          <p>
            We do not endorse any of the third-party vendors, pilots or service providers on the Platform, nor provide any guarantee as to their products and/or services.
          </p>
          <p>
            You acknowledge that the agreement for the provision of goods and services is between the third-party vendor/service provider and the User, and as such, any breach of contract and any claim arising from such breach is the subject matter of the third-party vendor/service provider and the User alone. We are in no way a party to such breach or involved in any action or proceeding arising from the same breach. The actions/proceedings arising from such breach shall be between the third-party vendor/service provider and the User directly.
          </p>
          <p>
            You release and indemnify us and/or any of our officers and representatives from any cost, damage, liability or other consequence of any of the actions of the third-party vendors, service providers or pilots on the Platform and specifically waive any claims that you may have in this behalf under any applicable law.
          </p>
          <p>
            We will be entitled to enter into any tie-up in terms of joint-venture or otherwise with any other institution engaged in the business of providing services analogous and/or similar to those herein contained. In such case, depending upon the modality and the mechanism as may be devised, you will be provided with the services by Flyhub jointly and/or severally with the party/parties in joint venture. You hereby give Your irrevocable consent and permission to such a tie-up. In the event of such a tie-up, the terms and conditions herein contained will mutatis mutandis become applicable in respect of such tie-up arrangement also.
          </p>
          <div className="disclaimer-box">
            <strong>DISCLAIMER:</strong> Due to some technical issues, typographical or human errors, images, ratings, descriptions, prices, vendor details, and any information related to vendors, users or content may be incorrectly reflected on the Platform. We do not take any responsibility for the reliance placed on such incorrect information. We assume that the goods and services listed on the Platform are authentic and accurate, and the vendors and users have the authority to carry on the transactions allowed, facilitated or otherwise accessible on or through the Platform.
          </div>
        </div>

        <div className="section-title">PAYMENT FOR SERVICES</div>
        <div className="terms-section">
          <p>
            The Users shall make payments for all products and services through the Platform alone.
          </p>
          <p>
            You agree and acknowledge that for undertaking any financial transaction through the Platform, we may undertake user due diligence measures and seek mandatory information required for KYC purposes that you are obliged to provide.
          </p>
          <p>
            We may obtain sufficient information to establish, to our satisfaction, your identity and the purpose of the intended nature of the relationship between the User and the third-party vendor/service provider.
          </p>
          <p>
            You agree and understand that you shall ensure that any payment is remitted only through your bank account or from a joint bank account in which you are a joint holder. In the event payment is remitted through a bank account opened in the name of a third party i.e. not being in your name, you agree and acknowledge that we may undertake enhanced due diligence measures including any documentation to satisfy the due diligence requirements. You further agree and acknowledge that in line with the requirements and obligations under the applicable laws, all refunds shall be processed by us to the bank account which was used to remit the payment.
          </p>
        </div>

        <div className="section-title">PAYMENT MECHANISM</div>
        <div className="terms-section">
          <p>
            To process financial transactions, we use third-party electronic payment processors or service providers (ESPs). You agree to be certain by the terms and conditions of use of each appropriate ESP. In the event of conflict between these Agreements and the ESP's terms and conditions, these Agreements shall prevail.
          </p>
          <p>
            Any information entered by the User when transacting on the Platform is encrypted to protect the User against unintentional disclosure to third parties. The User's credit and debit card information is not received, stored by or retained by the Company in any manner. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided, and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.
          </p>
          <p>
            The User is hereby expressly made aware that his/her financial statements will reflect that a payment has been made in favour of the Company. The User is further aware that in case of Third-Party statements including bank and credit card statements, the merchant name may appear in an abbreviated format and the Company has no control over the same.
          </p>
          <p>
            Users are requested to provide valid, accurate and complete information about your identity, payment account details (Card information, Bank account information and wallet credentials), Biller information and the payment information (payment amount and transaction description). The Company reserves the right to terminate User account or refuse your current and future use of Service in case your information is found suspicious.
          </p>
          <p>
            The Company assumes no responsibility and shall incur no liability if it is unable to affect any payment instruction owing to any one or more of the following circumstances:
          </p>
          <ul className="bullet-list">
            <li>If the Payment Instructions issued by you is/are incomplete, inaccurate, invalid</li>
            <li>If the Payment Account has insufficient funds/limits to cover for the amount as mentioned in the Payment Instructions</li>
            <li>If your bank or the wallet service refuses or delays honouring the Payment Instructions</li>
            <li>If payment is not processed by biller upon receipt</li>
            <li>If the User crosses transaction limit/amount limit decided by wallet services, payment gateways and banks</li>
            <li>Circumstances beyond the control of the Company (including natural calamities, issues with payment system, power failures, etc.)</li>
          </ul>
          <p>
            If money gets deducted from the User controlled account/wallet and the payment is not reflected in the User's account pertaining to the Platform, the User is requested to contact us at sales@flyhub.in. Your payment will be reflected within 48-72 hours if the transaction is successful at the payment gateway partners. If your payment status is not updated in the given time frame, please contact the bank for further enquiries. The Company does not take responsibility for such cases and payment will reflect in your bank account as per relevant Bank's policies.
          </p>
        </div>

        <div className="section-title">USER OBLIGATIONS</div>
        <div className="terms-section">
          <p>
            You are a restricted user of this Platform.
          </p>
          <p>
            You are bound not to cut, copy, distribute, modify, recreate, distribute, disseminate, post, publish or create derivative works from, transfer or sell any information obtained from the Platform save those that are present on the Flyhub blog and where sharing has been enabled in words or by using pictures/icons by us. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information within the content of the Platform is not permitted.
          </p>
          <p>
            You agree not to access (or attempt to access) the Platform and/or the materials or Services by any means other than through the interface that is provided by the Platform. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Platform are hereby expressly prohibited.
          </p>
          <p>
            In places where this Platform allows you to post or upload data/information, you undertake to ensure that such material is not offensive and in accordance with applicable laws. In the event you are asked to review any service, product or any vendor, you agree to be fair, accurate and non-disparaging while leaving comments, feedbacks, testimonials or reviews on or about the vendors, products or Services.
          </p>
          <p>
            You undertake not to host, display, upload, modify, publish, transmit, update or share any information that:
          </p>
          <ul className="bullet-list">
            <li>belongs to another person and to which the user does not have any right</li>
            <li>is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, religiously, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever</li>
            <li>harm minors in any way</li>
            <li>infringes any patent, trademark, copyright or other proprietary rights</li>
            <li>violates any law for the time being in force</li>
            <li>deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature</li>
            <li>impersonates another person</li>
            <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource, or</li>
            <li>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation</li>
            <li>encourages hatred, violence and discrimination in any form</li>
          </ul>
          <p>
            The User shall not:
          </p>
          <ul className="bullet-list">
            <li>Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others</li>
            <li>Engage in any activity that interferes with or disrupts access to the Platform or the servers and networks which are connected to the Platform</li>
            <li>Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity</li>
            <li>Upload, distribute or otherwise make available content that contain viruses, corrupted content or any software or program that may damage the operation of the Platform or another's operation of the Platform</li>
            <li>Probe, scan or test the vulnerability of the Platform or any network connected to the Platform, nor breach the security or authentication measures on the Platform or any network connected to the Platform. You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to the Platform, or any other customer of the Platform, including any User Account not owned by you, to its source, or exploit the Platform or Service or information made available or offered by or through the Platform, in any way whether or not the purpose is to reveal any information, including but not limited to personal identification information, as provided for by the Platform</li>
            <li>Disrupt or interfere with the security of, or otherwise cause harm to, the Platform, systems resources, accounts, passwords, servers or networks connected to or accessible through the Platform or any affiliated or linked sites</li>
            <li>Collect or store data about other Users in connection with the prohibited conduct and activities set forth in this section</li>
            <li>Use the Platform or any material or Content for any purpose that is unlawful or prohibited by these Terms, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Platform or other third parties</li>
            <li>Violate any code of conduct or other guidelines, which may be applicable for or to any particular Service</li>
            <li>Publish, post, disseminate information that is false, inaccurate or misleading</li>
            <li>Create liability for us or cause us to lose (in whole or in part) the services of our internet service provider (ISPs) or other suppliers/service providers</li>
          </ul>
          <p>
            By using the Application or the Service, you further agree that:
          </p>
          <ul className="bullet-list">
            <li>You will only use the Service or download the Application for Your sole, personal use and will not resell or assign it to a third party</li>
            <li>You will not use an account that is subject to any rights of a person other than You without appropriate authorization</li>
            <li>You will provide Flyhub with such information and documents which Flyhub may reasonably request</li>
            <li>You will only use an authorized network to avail the Service, and</li>
            <li>You are aware of and shall comply with the Information Technology Act, 2000 and the rules, regulations and guidelines notified thereunder</li>
          </ul>
          <p>
            It shall be a violation of these Terms of Use to use any information obtained from the Platform in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than us without our prior explicit consent.
          </p>
          <p>
            We reserve the right to immediately terminate the Service and the use of the Platform in the event of non-compliance with any of the above requirements.
          </p>
          <p>
            We can, and you hereby expressly authorize us to, disclose any information about you to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.
          </p>
          <p>
            You understand that we have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Platform) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or summons.
          </p>
        </div>

        <div className="section-title">PROFANITY</div>
        <div className="terms-section">
          <p>
            The User shall, in all interactions with Flyhub staff and employees, be courteous and respectful. In the event the User employs language or behaviour that is rude, inappropriate, threatening or abusive, Flyhub shall have the right to end the communication with the User, suspend/terminate the account of the User and pursue such legal action against the User as deemed appropriate.
          </p>
        </div>

        <div className="section-title">COMMUNICATIONS</div>
        <div className="terms-section">
          <p>
            By using this Platform, it is deemed you are interested in availing and purchasing the products/services that you have selected on the marketplace. You hereby agree that we may contact you either electronically or through phone, to understand your interest in the selected products and services and to assist with your requirement. You also agree that we reserve the right to make your details available to our affiliates and partners and you may be contacted by the affiliates and partners for information and for sales through email, telephone and/or SMS. You agree to receive promotional materials and/or special offers from us through email or SMS.
          </p>
          <p>
            You may also be contacted by third-party vendors or service providers whose services you avail through the Platform or by service providers with whom we have entered into a contract in furtherance of our rights, duties and obligations under this document and all other policies followed by us.
          </p>
          <p>
            The consent to be contacted is for purposes that include but are not limited to clarification calls and marketing and promotional calls.
          </p>
          <p>
            You agree and permit Flyhub to share any information provided by You with third parties in order to facilitate provision of certain value-added services offered by such third parties to You and/or to provide certain value-added services to You by Flyhub. You hereby expressly consent to receive communications from Flyhub/ third parties offering value-added services to You through Your registered phone number and/or email id and/or the Platform. You agree that You will not hold Flyhub responsible for any such communications received from third parties, nor will any such communication amount to spam, unsolicited communication or a violation of Your registration on the national do not call registry.
          </p>
          <p>
            The sharing of the information provided by you is governed by the Privacy Policy. You hereby unconditionally consent that such communications via SMS, Chat and/or voice call is (a) upon your request and authorization, (b) transactional and not an unsolicited commercial communication as per the guidelines of Telecom Regulation Authority of India (TRAI) and (c) in compliance with the relevant guidelines of TRAI or such other authority in India.
          </p>
          <p>
            You hereby agree and undertake to indemnify us against all types of losses and damages incurred by us due to any action taken by TRAI, Access Providers (as per TRAI regulations) or any other authority due to any erroneous compliant raised by you against us with respect to the intimations mentioned above or due to a wrong number or email id being provided by you for any reason whatsoever.
          </p>
          <p>
            In the event you do not wish to be contacted as set forth in this section and as set forth in the Privacy Policy, you may opt out by contacting us at sales@flyhub.in. Further, you may unsubscribe from our mailing list by clicking the unsubscribe button provided in the mails.
          </p>
        </div>

        <div className="section-title">INTELLECTUAL PROPERTY RIGHTS</div>
        <div className="terms-section">
          <p>
            This Platform and the Information available on or through the Services and/or the Platform, including without limitation, text, photographs, graphics, and video and audio content, but excluding vendor Content and User Content, is the sole and exclusive property of the Company and/or its licensors and is protected by copyright, trademark, patent, and trade secret laws, other proprietary rights, and international treaties. We retain all right, title and interest (including all copyright, trademark, patent, trade secrets and all other intellectual property rights) in the Platform, except as specified to the contrary.
          </p>
          <p>
            You acknowledge that the Services and any underlying technology or software used in connection with the Services contain the company proprietary information.
          </p>
          <p>
            There are a number of proprietary logos, service marks and trademarks found on this Platform whether owned/used by the Company or any other third party. By displaying them on Platform, the Company is not granting you any license to utilize the proprietary logos, service marks or trademarks.
          </p>
          <p>
            From time to time, the Company may post comments or articles on the Platform. These articles are the Intellectual Property of the Company and you are prohibited from posting, reproducing, publishing, amending or editing such articles save where the sharing of such content is allowed by Us. In the event you have an issue with any article so posted, you may report the same via mail and we may look into it. We are under no obligation to remove such articles and the final decision lies with us.
          </p>
          <p>
            We are not in any way liable to you for any loss arising to you from activities that include but are not limited to our negligence, breach of contract, Intellectual Property infringement, breach of laws etc.
          </p>
          <p>
            We give you permission to use the aforementioned content in accordance with these Terms and do not transfer any intellectual property rights to you by virtue of permitting your use of the Services. You may print, download and store information from the Platform for your own convenience, but you may not copy, distribute, republish, sell, or exploit any of the content, or exploit the Platform in whole or in part, for any commercial gain or purpose whatsoever save as set forth in these Terms. The Company does not grant you any express or implied rights and all rights in the Platform and the Services not expressly granted by the Company are retained by the Company.
          </p>
          <p>
            From time to time, our Platform may have external links connected to other websites of Third Parties. We are in no way liable for the information found on the external websites. External websites may have their own policies and we are in no way responsible for any loss or damage cause by them to you. You are advised to use your own discretion in the navigation and use of external websites.
          </p>
        </div>

        <div className="section-title">OUR USE OF USER CONTENT</div>
        <div className="terms-section">
          <p>
            You grant Flyhub, its affiliates and concerns, a non-exclusive, royalty-free, transferable, sublicensable, worldwide license to store, display, reproduce and distribute your User Content on the Platform for the purposes of operating, developing, providing and using our Services. Nothing in these Terms shall restrict other legal rights we may have to User Content under other licenses. We reserve the right to remove User Content for any reason, including a violation or an apparent violation of these Terms or our policies, as we may solely determine.
          </p>
          <p>
            Following termination or deactivation of your account, or your removal of any User Content from the Platform, we may, but shall not be bound to, retain such Content for a commercially reasonable period of time for backup, archival, or audit purposes. It is specified that the Company shall have the right to remove all User Content following termination or deactivation of your account.
          </p>
        </div>

        <div className="section-title">DISCLAIMER OF WARRANTIES AND LIABILITIES</div>
        <div className="terms-section">
          <p>You expressly understand and agree that, to the maximum extent permitted by applicable law:
            
          </p>
          <p>
            The platform, services and other materials are provided by this platform is on an "as is" basis without warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose. without limiting the foregoing, the company makes no warranty that:
          </p>
          <ul className="bullet-list">
            <li>Your requirements will be met or that services provided will be uninterrupted, timely, secure or error-free</li>
            <li>Materials or information provided will be effective, accurate or reliable</li>
            <li>The vendors and their services displayed to you will be accurate or updated, or that</li>
            <li>Any errors or defects in the platform, services, or other materials will be corrected</li>
          </ul>
          <p>
            The user understands and agrees that any material or data downloaded or otherwise obtained through the platform is done entirely at their own discretion and risk and they will be solely responsible for such actions. the company accepts no liability for any errors or omissions with respect to any information provided to you whether on behalf of itself or third parties.
          </p>
          <p>
            To the maximum extent permitted by applicable law, we will have no liability related to user content or vendor content arising under intellectual property rights, libel, privacy, publicity, obscenity, or other laws. the company also disclaims all liability with respect to the misuse, loss, modification, or unavailability of any user content.
          </p>
        </div>

        <div className="section-title">INDEMNIFICATION AND LIMITATION OF LIABILITY</div>
        <div className="terms-section">
          <p>
            You agree to indemnify, defend and hold harmless this platform, including but not limited to the company, its affiliates, agents, directors and employees from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by us that arise out of, result from, or may be payable by virtue of, (i) any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by you pursuant to these terms of use, (ii) your violation or breach of any term of these user terms or any applicable law or regulation, whether or not referenced herein, and/or (iii) your violation of any rights of any third party, including those of the vendors. further, you agree to hold us harmless against any claims arising due to or arising out of or in connection with your use of the platform, any claim that your material caused damage to a third party, your violation of the terms of use, or your violation of any rights of another, including any intellectual property rights.
          </p>
          <p> In no event shall we, our officers, directors, employees, partners or suppliers be liable to you or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not we have been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortious action, or any other claim arising out of or in connection with your use of or access to the platform, services or materials.   </p>
          <p>We shall not be liable for any failure to perform any obligations under this user terms, if the performance is prevented, hindered or delayed by a force majeure event and in such case our obligations under this user terms shall be suspended for so long as the force majeure event continues.
            </p>
        <p>In addition, and without limiting the foregoing, to the fullest extent permitted by applicable law, in no event will flyhub's aggregate liability arising out of or in connection with these user terms or the services rendered hereunder, whether in contract, tort (including negligence, product liability or other theory), warranty or otherwise, exceed the amount of rs. 1000 (rupees one thousand only).
          </p>
          <p>If applicable law does not permit the exclusion of certain warranties or the limitation or exclusion of liability, the scope and duration of such warranty exclusions and the extent of the liability of flyhub shall be the minimum permitted under applicable law.
            </p>
          
          <p>
            The Material on this site comprise Flyhub's Views; they do not constitute legal or other professional advice. You should consult your professional adviser for legal and other advise.
          </p>
          <p>
            This site offers links to other sites thereby enabling you to leave this site and go directly to the linked site. Flyhub is not responsible for the content of any linked site or any link in a linked site. Flyhub is not responsible for any transmission received from any linked site. The Links are provided to assist visitors to the Flyhub Site and the inclusion of a link does not imply that Flyhub endorses or has approved the linked site.
          </p>
          <p>
            To the maximum extent permitted by applicable law, The Flyhub Entities shall not be liable for any indirect, Incidental, Special, Consequential or punitive Damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of our inability to access or use the services, (ii) any conduct or content of any third party on the services, including without limitation, any defamatory, offensive or illegal conduct of other users or third parties, (iii) any contain obtained from the services, or(iv) unauthorised access, use or alteration of your transmissions or content. In no event shall the aggregate liability of the Flyhub Entities exceed the greater of Fifty Pound sterling (£5000) or the amount you paid to Flyhub, if any, in the past 1 month for the services giving rise to the claim. The limitations of this subsection shall apply to any theory of liability, whether based on warranty, contract, statute, tort (including negligence) or otherwise, and whether or not the Flyhub entities have been informed the possibility of any such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.
          </p>
        </div>

        <div className="section-title">TERM, TERMINATION, SURVIVAL</div>
        <div className="terms-section">
          <p>
            This Agreement shall become effective from the date of registration of the User account and shall continue in effect thereafter unless terminated as set forth below.
          </p>
          <p>
            You are entitled to terminate the agreement at all times by deleting the mobile application from your mobile/operating system, thus disabling the use by You of the mobile application.
          </p>
          <p>
            Flyhub is entitled to terminate the agreement at all times and with immediate effect by disabling Your use of the Platform and the Service if You (a) violate or breach any term of these User Terms, or (b) in the opinion of Flyhub, misuse the Platform or the Service. Flyhub is not obliged to give notice of the termination of the agreement in advance. After termination Flyhub will give notice thereof in accordance with these User Terms.
          </p>
          <p>
            Termination of this agreement will not prejudice accrued rights of either Flyhub or You.
          </p>
          <p>
            Any terms or conditions of this Agreement which by their express terms extend beyond termination or expiration of this Agreement or which by their nature will so extend, will survive and continue in full force and effect after any termination or expiration of this Agreement.
          </p>
        </div>

        <div className="section-title">APPLICATION TERMS</div>
        <div className="terms-section">
          <p>
            Subject to Your compliance with these User Terms, Flyhub grants You a limited, revocable, non-exclusive, non-transferable and non-sublicensable license to download and install a copy of the Application on a single mobile device that You own or control and to run such copy of the Application solely for Your own personal use and to use the Platform.
          </p>
          <p>
            Upon download and installation of the mobile application, you grant the following permissions to the application to perform the following actions on the device you have installed the application on:
          </p>
          <ul className="bullet-list">
            <li>to retrieve information about the device</li>
            <li>to retrieve information about other applications running on the device the application has been installed on</li>
            <li>to access information about accounts on the device</li>
            <li>to read from, write on, modify and delete data pertaining to contacts on the device</li>
            <li>to access information about networks, access networks (including WiFi networks), receive and send data through the network</li>
            <li>to determine your approximate location from sources like, but not limited to, mobile towers and connected WiFi networks</li>
            <li>to determine your exact location from sources such as, but not limited to, GPS</li>
            <li>to access the model number, IMEI number and details about the operating system of the device the application has been installed on, as well as the phone number of the device</li>
            <li>to detect when the device had been switched off and switched on, and to identify the status of the device</li>
            <li>to read from, write on, modify and delete data pertaining to the application on the device's hard disk and/or external storage</li>
            <li>to read from, write on, modify and delete data pertaining to Photos/ Media Files on the device's hard disk and/or external storage</li>
            <li>to access the camera on the device and record photographs and videos</li>
            <li>to access the microphone on the device and record audio</li>
            <li>to access and change the display and sound settings of the device</li>
            <li>to capture audio output</li>
            <li>to interact across users on the device</li>
            <li>to pair with Bluetooth devices</li>
            <li>to run at startup of the device</li>
            <li>to draw over other apps on the device</li>
            <li>to control vibration of the device, and</li>
            <li>to prevent the device from sleeping</li>
          </ul>
        </div>

        <div className="section-title">DISPUTE RESOLUTION</div>
        <div className="terms-section">
          <p>
            All disputes between the User and the Company arising from the use of the Platform by the User shall be resolved amicably by mediation or negotiation, failing which they shall be referred to binding arbitration by a Sole Arbitrator. The Sole Arbitrator shall be jointly appointed by the Company and the User. The arbitral award shall be final and binding on the parties and there shall be no further remedy available. The arbitration proceedings will take place in Bengaluru, Karnataka and will be in English. The provisions of the Arbitration and Conciliation Act, 1996 shall apply to the arbitration.
          </p>
          <p>
            The Courts in Bengaluru, Karnataka shall have the jurisdiction for all suits arising out of or in connection with this Agreement.
          </p>
          <p>
            Any grievances, issues, queries, complaints or information that you wish to communicate to us can be addressed to our Grievance officer at sales@flyhub.in.
          </p>
        </div>

        <div className="section-title">MISCELLANEOUS TERMS</div>
        <div className="terms-section">
          <p>
            The company reserves its exclusive right in its sole discretion to alter, limit or discontinue the Platform or any material posted herein, in any respect. The company shall have no obligation to take the needs of any user into consideration in connection therewith.
          </p>
          <p>
            The company reserves its right to deny in its sole discretion any user access to this Platform or any portion hereof without notice.
          </p>
          <p>
            If any provision of this Agreement is held to be unlawful, void, invalid or otherwise unenforceable, then that provision will be limited or eliminated from this Agreement to the minimum extent required, and the remaining provisions will remain valid and enforceable.
          </p>
          <p>
            No waiver by the company of any provision of these Terms shall be binding except as set forth in writing and signed by its duly authorized representative.
          </p>
          <p>
            From time to time, the Platform may automatically check the version of the mobile application installed on the device of the User and, if applicable, provide suitable updates (hereinafter referred to as "Updates"). Updates may contain, without limitation, bug fixes, patches, enhanced functionality, plugins and new versions of the application. By using the Platform, you authorize the automatic download and installation of Updates and agree to download and install Updates manually if necessary.
          </p>
          <p>
            Flyhub reserves the right, at its sole discretion, to modify or replace, in part or full, any of these User Terms.
          </p>
          <p>
            Flyhub shall not be required to notify you of any changes made to these User Terms. The revised User Terms shall be made available on the Site. You are requested to regularly visit the site to view the most current User Terms. You can determine when Flyhub last modified the User Terms by referring to the "Last Updated" legend above. It shall be your responsibility to check these User Terms periodically for changes. Flyhub may require you to provide your consent to the updated User Terms in a specified manner prior to any further use of the Site and the Services. If no such separate consent is sought, your continued use of the Site following the changes to the User Terms will constitute Your acceptance of those changes. Your use of the site and the Services is subject to the most current version of the User Terms made available on the site at the time of such use.
          </p>
          <p>
            Flyhub may give notice by means of a general notice on the Service or Application, or by electronic mail to your email address or a message on your registered mobile number, or by written communication sent by regular mail to your address on record in Flyhub's account information.
          </p>
        </div>

        <div className="section-divider"></div>
      </main>
    </div>
  );
};

export default TermsAndConditions;